### ISSUE TITLE
주문 완료 메일 발송

### ISSUE THREAD

**Issue by hseungho** [Liberty52/Liberty52-BE#133]
# 주문 완료 메일 발송

- 카드결제 주문 완료 메일 발송 : 주문 시 -> 수취자에게 발송
  - (결제금액, 카드사, 카드번호, 결제일자, 할부개월)

- 가상계좌 입금 확인 주문 완료 메일 발송 : 관리자가 입금 확인 시 -> 수취자에게 발송

**Comment by jinlee0** [comment]
알림톡으로 하는 건 어떨까요? 아니면 둘 다?
